def modfind(protein):
	#Create a codon frequency dictionary
    tableCount = {'A': 4,'C': 2,'D': 2,'E': 2,'F': 2,'G': 4,'H': 2,'I': 3,'K': 2,'L': 6,'M': 1,'N': 2,'P': 4,'Q': 2,'R': 6,'S': 6,'T': 4,'V': 4,'W': 1,'Y': 2, '*':3}

    protein = protein + '*'

    C = 1
    for aminoAcid in protein:
        C = C * tableCount[aminoAcid]

    return C%1000000

print(modfind('MA'))

#######################################################################


table = {
        'UUU': 'F', 'CUU': 'L', 'AUU': 'I', 'GUU': 'V',
        'UUC': 'F', 'CUC': 'L', 'AUC': 'I', 'GUC': 'V',
        'UUA': 'L', 'CUA': 'L', 'AUA': 'I', 'GUA': 'V',
        'UUG': 'L', 'CUG': 'L', 'AUG': 'M', 'GUG': 'V',
        'UCU': 'S', 'CCU': 'P', 'ACU': 'T', 'GCU': 'A',
        'UCC': 'S', 'CCC': 'P', 'ACC': 'T', 'GCC': 'A',
        'UCA': 'S', 'CCA': 'P', 'ACA': 'T', 'GCA': 'A',
        'UCG': 'S', 'CCG': 'P', 'ACG': 'T', 'GCG': 'A',
        'UAU': 'Y', 'CAU': 'H', 'AAU': 'N', 'GAU': 'D',
        'UAC': 'Y', 'CAC': 'H', 'AAC': 'N', 'GAC': 'D',
        'UAA': '*', 'CAA': 'Q', 'AAA': 'K', 'GAA': 'E',
        'UAG': '*', 'CAG': 'Q', 'AAG': 'K', 'GAG': 'E',
        'UGU': 'C', 'CGU': 'R', 'AGU': 'S', 'GGU': 'G',
        'UGC': 'C', 'CGC': 'R', 'AGC': 'S', 'GGC': 'G',
        'UGA': '*', 'CGA': 'R', 'AGA': 'R', 'GGA': 'G',
        'UGG': 'W', 'CGG': 'R', 'AGG': 'R', 'GGG': 'G'
    }

C = {}

for key, value in table.items():
    if value in C:
        C[value] += 1
    else:
        C[value] = 1

Protein = 'MAGILTDRIQTMEWPISWIASGHRHIMVLPSVCPKVYCKEQSANDQKNMPQLHKEWYFYRPVFGFPSIGNIHRQYDDRQQWFQVVFWYTPSGCTGLILLPAFTVYWDNHRMYNCGPCRSEPFDYFCGFFTDQYEFEKMFMPVIFKPEALMIFKTDEWVHKGNTYCRRHAKHSSDTYVRQYFWQRDSKDSRISYNKWMYDPSGVVSIAGCKCGEKTMDPHSMHNWRCTQLFVHPKYNYFLLKDPSTGYDTIDRHNAKVAESIPSFVCMPKRKCLGMIFVMGLMPNPAISWARKVHMLECNPSHCPYWIERWPERTGSCACLRHICWRYIQCGMIYNTWRKIFWNKCLDGHCENCNKKHYIQGEVYTTCDFLNNCCQQCAGPNACSVNGDHYYIKAEPYNKENGSNLQMTSHRPWSWRVREMIVNVSNSVMLIVRDIGPQAYQSEYTPIFKHHYSNSRGWQLNQFTLRHCVAAIYKEHIRKKVNPSGKEHWQCVVHHMDGVHFINIHRYYTACCLMYYKSEGPLGQMATKYAWPDAMARHVIHHYHFGPWDNGPKWQWGSMCEWGNSRIKMIIATDNLWMDNKGQRTENAGCGFFSWFMASLPEMCNFVAMFEWDKWDLKNFPPPCKEHMRQIAACLTDVENTKQVGNYKHDGNSYNSIFHPDYMEITFYVFVCKSCDKGTVHRNCQWGVSKYTSLRNLKIAQPVNHRILHNMLDPIPNVIYYWPTHHCKYCDNFRYMSFNHICNQCDKCADCRKWILYLQEPIAGDPGYRDTQSLCYHECRIDDASRLPCRPSLIGNWMNNGTIVMMPWIEITLWPGPFQEKDSASFKGKWCWEHCARNIRLGRFQQIKNPFFKRDWKNWDESLMFLYCCHYSLTEWCTHFKERRLYHQYHITQSPVCLPQYRFWPCASSVFYAVYELHTFWMSWQQIWIAESNWLGLVDFNMCSNSDGLKRIVIKHEQPCTWYLGPNWYMRDSCHPGCNEHSAELMKWITLQGGCAF'
Protein = Protein + '*'
possibleRNA = 1

for eachAminoAcid in Protein:
    possibleRNA *= C[eachAminoAcid]

print(possibleRNA%1000000)



